name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: Analize with Sonar
      if: github.event_name == 'push'
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
         -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
         -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
